//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Application.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact request has already been promoted..
        /// </summary>
        public static string BusinessRule_ContactRequestAlreadyPromoted {
            get {
                return ResourceManager.GetString("BusinessRule_ContactRequestAlreadyPromoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reCAPTCHA. Please try again..
        /// </summary>
        public static string BusinessRule_InvalidReCAPTCHA {
            get {
                return ResourceManager.GetString("BusinessRule_InvalidReCAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this category — {0} contact(s) still reference it..
        /// </summary>
        public static string CannotDelete_CategoryReferenced {
            get {
                return ResourceManager.GetString("CannotDelete_CategoryReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this company — {0} experience(s) still reference it..
        /// </summary>
        public static string CannotDelete_CompanyReferenced {
            get {
                return ResourceManager.GetString("CannotDelete_CompanyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this institution — {0} education(s) still reference it..
        /// </summary>
        public static string CannotDelete_InstitutionReferenced {
            get {
                return ResourceManager.GetString("CannotDelete_InstitutionReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this proficiency level — {0} keyword(s) still reference it..
        /// </summary>
        public static string CannotDelete_ProficiencyReferenced {
            get {
                return ResourceManager.GetString("CannotDelete_ProficiencyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this tag — {0} idea(s) still reference it..
        /// </summary>
        public static string CannotDelete_TagReferenced {
            get {
                return ResourceManager.GetString("CannotDelete_TagReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        public static string NotFound_Category {
            get {
                return ResourceManager.GetString("NotFound_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found..
        /// </summary>
        public static string NotFound_Company {
            get {
                return ResourceManager.GetString("NotFound_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found..
        /// </summary>
        public static string NotFound_Contact {
            get {
                return ResourceManager.GetString("NotFound_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact request not found..
        /// </summary>
        public static string NotFound_ContactRequest {
            get {
                return ResourceManager.GetString("NotFound_ContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education not found..
        /// </summary>
        public static string NotFound_Education {
            get {
                return ResourceManager.GetString("NotFound_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience not found..
        /// </summary>
        public static string NotFound_Experience {
            get {
                return ResourceManager.GetString("NotFound_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea not found..
        /// </summary>
        public static string NotFound_Idea {
            get {
                return ResourceManager.GetString("NotFound_Idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution not found..
        /// </summary>
        public static string NotFound_Institution {
            get {
                return ResourceManager.GetString("NotFound_Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction not found..
        /// </summary>
        public static string NotFound_Interaction {
            get {
                return ResourceManager.GetString("NotFound_Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction not found..
        /// </summary>
        public static string NotFound_Introduction {
            get {
                return ResourceManager.GetString("NotFound_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword not found..
        /// </summary>
        public static string NotFound_Keyword {
            get {
                return ResourceManager.GetString("NotFound_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network profile not found..
        /// </summary>
        public static string NotFound_NetworkProfile {
            get {
                return ResourceManager.GetString("NotFound_NetworkProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note not found..
        /// </summary>
        public static string NotFound_Note {
            get {
                return ResourceManager.GetString("NotFound_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency level not found..
        /// </summary>
        public static string NotFound_ProficiencyLevel {
            get {
                return ResourceManager.GetString("NotFound_ProficiencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found..
        /// </summary>
        public static string NotFound_Project {
            get {
                return ResourceManager.GetString("NotFound_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found..
        /// </summary>
        public static string NotFound_Tag {
            get {
                return ResourceManager.GetString("NotFound_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar filename is required..
        /// </summary>
        public static string Validation_AvatarFilenameRequired {
            get {
                return ResourceManager.GetString("Validation_AvatarFilenameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA verification is required..
        /// </summary>
        public static string Validation_CaptchaTokenRequired {
            get {
                return ResourceManager.GetString("Validation_CaptchaTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        public static string Validation_CategoryNameRequired {
            get {
                return ResourceManager.GetString("Validation_CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Validation_ContactEmailRequired {
            get {
                return ResourceManager.GetString("Validation_ContactEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one identifying field (name, email, or LinkedIn) is required..
        /// </summary>
        public static string Validation_ContactIdentifyingField {
            get {
                return ResourceManager.GetString("Validation_ContactIdentifyingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is required..
        /// </summary>
        public static string Validation_ContactMessageRequired {
            get {
                return ResourceManager.GetString("Validation_ContactMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string Validation_ContactNameRequired {
            get {
                return ResourceManager.GetString("Validation_ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is required..
        /// </summary>
        public static string Validation_ContactSubjectRequired {
            get {
                return ResourceManager.GetString("Validation_ContactSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain is required..
        /// </summary>
        public static string Validation_DomainRequired {
            get {
                return ResourceManager.GetString("Validation_DomainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before start date..
        /// </summary>
        public static string Validation_EndDateBeforeStart {
            get {
                return ResourceManager.GetString("Validation_EndDateBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image filename is required..
        /// </summary>
        public static string Validation_ImageFilenameRequired {
            get {
                return ResourceManager.GetString("Validation_ImageFilenameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required for the {0} translation..
        /// </summary>
        public static string Validation_NameRequiredForLanguage {
            get {
                return ResourceManager.GetString("Validation_NameRequiredForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note content is required..
        /// </summary>
        public static string Validation_NoteContentRequired {
            get {
                return ResourceManager.GetString("Validation_NoteContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority is required..
        /// </summary>
        public static string Validation_PriorityRequired {
            get {
                return ResourceManager.GetString("Validation_PriorityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A proficiency level must be selected..
        /// </summary>
        public static string Validation_ProficiencyRequired {
            get {
                return ResourceManager.GetString("Validation_ProficiencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL is required..
        /// </summary>
        public static string Validation_ProjectUrlRequired {
            get {
                return ResourceManager.GetString("Validation_ProjectUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred-by name is required for warm introductions..
        /// </summary>
        public static string Validation_ReferredByNameRequired {
            get {
                return ResourceManager.GetString("Validation_ReferredByNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale must be between 0 and 100..
        /// </summary>
        public static string Validation_ScaleRange {
            get {
                return ResourceManager.GetString("Validation_ScaleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small avatar filename is required..
        /// </summary>
        public static string Validation_SmallAvatarFilenameRequired {
            get {
                return ResourceManager.GetString("Validation_SmallAvatarFilenameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        public static string Validation_StatusRequired {
            get {
                return ResourceManager.GetString("Validation_StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary is required..
        /// </summary>
        public static string Validation_SummaryRequired {
            get {
                return ResourceManager.GetString("Validation_SummaryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name is required..
        /// </summary>
        public static string Validation_TagNameRequired {
            get {
                return ResourceManager.GetString("Validation_TagNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string Validation_TitleRequired {
            get {
                return ResourceManager.GetString("Validation_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required for the {0} translation..
        /// </summary>
        public static string Validation_TitleRequiredForLanguage {
            get {
                return ResourceManager.GetString("Validation_TitleRequiredForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one translation is required..
        /// </summary>
        public static string Validation_TranslationsRequired {
            get {
                return ResourceManager.GetString("Validation_TranslationsRequired", resourceCulture);
            }
        }
    }
}
