version: "3.9"

secrets:
  kulku-default-conn_v3:
    external: true
  kulku-user-conn_v3:
    external: true
  kulku-recaptcha-secret:
    external: true
  holdion-otlp-headers:
    external: true

services:
  api:
    image: ghcr.io/arawnik/kulku-api:stable
    secrets:
      - source: kulku-default-conn_v3
        target: default-conn
      - source: kulku-user-conn_v3
        target: user-conn
      - source: holdion-otlp-headers
        target: otlp-headers
      - kulku-recaptcha-secret
    volumes:
      - /var/www/manager/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ForceHttps
      - ASPNETCORE_ENVIRONMENT
      - Cors__AllowedOrigins
    ports:
      - target: 5144
        published: 5144
        protocol: tcp
        mode: host
    networks:
      - app_net
      - data_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

  admin:
    image: ghcr.io/arawnik/kulku-admin:stable
    secrets:
      - source: kulku-default-conn_v3
        target: default-conn
      - source: kulku-user-conn_v3
        target: user-conn
      - source: holdion-otlp-headers
        target: otlp-headers
    volumes:
      - /var/www/manager/letsencrypt:/etc/letsencrypt:ro
      - /var/www/jerejunttila/out:/app/assets:ro
    environment:
      - ForceHttps
      - ASPNETCORE_ENVIRONMENT
      - Management__MigrateOnStart
      - Management__ContactUrl
      - Assets__LocalPath
    ports:
      - target: 5090
        published: 5090
        protocol: tcp
        mode: host
    networks:
      - app_net
      - data_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

  client:
    image: ghcr.io/arawnik/kulku-client:stable
    volumes:
      - /var/www/jerejunttila/out/downloads:/app/public/static/downloads:ro
      - /var/www/jerejunttila/out/introductions:/app/public/static/introductions:ro
      - /var/www/jerejunttila/out/projects:/app/public/static/projects:ro
    environment:
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY
      - NEXT_PUBLIC_EN_HOSTS
      - NEXT_PUBLIC_FI_HOSTS
      - API_BASE_URL
      - BASE_PROTO
    ports:
      - target: 3000
        published: 8086
        protocol: tcp
        mode: host
    networks:
      - app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  app_net:
    driver: overlay

  data_net:
    external: true
