@Kulku.Web.Api_HostAddress = https://localhost:7219
@Lang = fi


# PROJECT

### Get all projects
GET {{Kulku.Web.Api_HostAddress}}/project/
Accept: application/json
Accept-Language: {{Lang}}

### Get project keywords
GET {{Kulku.Web.Api_HostAddress}}/project/keywords/SK
Accept: application/json
Accept-Language: {{Lang}}
