// <auto-generated />
using System;
using Kulku.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kulku.Persistence.Pgsql.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExperienceKeyword", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordsId")
                        .HasColumnType("uuid");

                    b.HasKey("ExperienceId", "KeywordsId");

                    b.HasIndex("KeywordsId");

                    b.ToTable("ExperienceKeyword");
                });

            modelBuilder.Entity("Kulku.Domain.Contacts.ContactRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.CompanyTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Language", "CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.EducationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EducationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.HasIndex("Language", "EducationId")
                        .IsUnique();

                    b.ToTable("EducationTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EndDate");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.ExperienceTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("Language", "ExperienceId")
                        .IsUnique();

                    b.ToTable("ExperienceTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.InstitutionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Language", "InstitutionId")
                        .IsUnique();

                    b.ToTable("InstitutionTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Introduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SmallAvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PubDate");

                    b.ToTable("Introductions");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.IntroductionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IntroductionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IntroductionId");

                    b.HasIndex("Language", "IntroductionId")
                        .IsUnique();

                    b.ToTable("IntroductionTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IdeaDomains");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaDomainTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IdeaDomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaDomainId", "Language")
                        .IsUnique();

                    b.ToTable("IdeaDomainTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaIdeaTag", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdeaTagId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId", "IdeaTagId");

                    b.HasIndex("IdeaTagId");

                    b.ToTable("IdeaIdeaTag");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaKeyword", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("IdeaKeyword");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaNotes");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("IdeaPriorities");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaPriorityTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdeaPriorityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaPriorityId", "Language")
                        .IsUnique();

                    b.ToTable("IdeaPriorityTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("IdeaStatuses");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaStatusTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("IdeaStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaStatusId", "Language")
                        .IsUnique();

                    b.ToTable("IdeaStatusTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("IdeaTags");
                });

            modelBuilder.Entity("Kulku.Domain.Network.CompanyNetworkProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyNetworkProfiles");
                });

            modelBuilder.Entity("Kulku.Domain.Network.CompanyNetworkProfileCategory", b =>
                {
                    b.Property<Guid>("CompanyNetworkProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NetworkCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyNetworkProfileId", "NetworkCategoryId");

                    b.HasIndex("NetworkCategoryId");

                    b.ToTable("CompanyNetworkProfileCategories");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorToken")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("NetworkCategories");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("NetworkContacts");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWarmIntro")
                        .HasColumnType("boolean");

                    b.Property<string>("NextAction")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NextActionDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferredByName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReferredByRelation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContactId");

                    b.HasIndex("Date");

                    b.ToTable("NetworkInteractions");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Display")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProficiencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProficiencyId");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.KeywordTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId", "Language")
                        .IsUnique();

                    b.ToTable("KeywordTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Proficiency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Proficiencies");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProficiencyTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProficiencyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProficiencyId", "Language")
                        .IsUnique();

                    b.ToTable("ProficiencyTranslations");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProjectKeyword", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("ProjectKeyword");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProjectTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Language")
                        .IsUnique();

                    b.ToTable("ProjectTranslations");
                });

            modelBuilder.Entity("ExperienceKeyword", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Projects.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kulku.Domain.Cover.CompanyTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Company", "Company")
                        .WithMany("Translations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Education", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.EducationTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Education", "Education")
                        .WithMany("Translations")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Experience", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.ExperienceTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Experience", "Experience")
                        .WithMany("Translations")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.InstitutionTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Institution", "Institution")
                        .WithMany("Translations")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.IntroductionTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Introduction", "Introduction")
                        .WithMany("Translations")
                        .HasForeignKey("IntroductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Introduction");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.Idea", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.IdeaDomain", "Domain")
                        .WithMany("Ideas")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Ideas.IdeaPriority", "Priority")
                        .WithMany("Ideas")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Ideas.IdeaStatus", "Status")
                        .WithMany("Ideas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaDomainTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.IdeaDomain", "IdeaDomain")
                        .WithMany("Translations")
                        .HasForeignKey("IdeaDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdeaDomain");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaIdeaTag", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.Idea", "Idea")
                        .WithMany("IdeaIdeaTags")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Ideas.IdeaTag", "IdeaTag")
                        .WithMany("IdeaIdeaTags")
                        .HasForeignKey("IdeaTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("IdeaTag");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaKeyword", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.Idea", "Idea")
                        .WithMany("IdeaKeywords")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Projects.Keyword", "Keyword")
                        .WithMany("IdeaKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaNote", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.Idea", "Idea")
                        .WithMany("Notes")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaPriorityTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.IdeaPriority", "IdeaPriority")
                        .WithMany("Translations")
                        .HasForeignKey("IdeaPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdeaPriority");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaStatusTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Ideas.IdeaStatus", "IdeaStatus")
                        .WithMany("Translations")
                        .HasForeignKey("IdeaStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdeaStatus");
                });

            modelBuilder.Entity("Kulku.Domain.Network.CompanyNetworkProfile", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kulku.Domain.Network.CompanyNetworkProfileCategory", b =>
                {
                    b.HasOne("Kulku.Domain.Network.CompanyNetworkProfile", "CompanyNetworkProfile")
                        .WithMany("CompanyNetworkProfileCategories")
                        .HasForeignKey("CompanyNetworkProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Network.NetworkCategory", "NetworkCategory")
                        .WithMany("CompanyNetworkProfileCategories")
                        .HasForeignKey("NetworkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyNetworkProfile");

                    b.Navigation("NetworkCategory");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkContact", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkInteraction", b =>
                {
                    b.HasOne("Kulku.Domain.Cover.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Network.NetworkContact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Keyword", b =>
                {
                    b.HasOne("Kulku.Domain.Projects.Proficiency", "Proficiency")
                        .WithMany("Keywords")
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proficiency");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.KeywordTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Projects.Keyword", "Keyword")
                        .WithMany("Translations")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProficiencyTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Projects.Proficiency", "Proficiency")
                        .WithMany("Translations")
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proficiency");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProjectKeyword", b =>
                {
                    b.HasOne("Kulku.Domain.Projects.Keyword", "Keyword")
                        .WithMany("ProjectKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kulku.Domain.Projects.Project", "Project")
                        .WithMany("ProjectKeywords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.ProjectTranslation", b =>
                {
                    b.HasOne("Kulku.Domain.Projects.Project", "Project")
                        .WithMany("Translations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Company", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Education", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Experience", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Institution", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Cover.Introduction", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.Idea", b =>
                {
                    b.Navigation("IdeaIdeaTags");

                    b.Navigation("IdeaKeywords");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaDomain", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaPriority", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaStatus", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Ideas.IdeaTag", b =>
                {
                    b.Navigation("IdeaIdeaTags");
                });

            modelBuilder.Entity("Kulku.Domain.Network.CompanyNetworkProfile", b =>
                {
                    b.Navigation("CompanyNetworkProfileCategories");
                });

            modelBuilder.Entity("Kulku.Domain.Network.NetworkCategory", b =>
                {
                    b.Navigation("CompanyNetworkProfileCategories");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Keyword", b =>
                {
                    b.Navigation("IdeaKeywords");

                    b.Navigation("ProjectKeywords");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Proficiency", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Kulku.Domain.Projects.Project", b =>
                {
                    b.Navigation("ProjectKeywords");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
