//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CvStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CvStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Web.Admin.Resources.CvStrings", typeof(CvStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Company.
        /// </summary>
        public static string Company_CreateModal {
            get {
                return ResourceManager.GetString("Company_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this company? This action cannot be undone..
        /// </summary>
        public static string Company_DeleteMessage {
            get {
                return ResourceManager.GetString("Company_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Company.
        /// </summary>
        public static string Company_DeleteTitle {
            get {
                return ResourceManager.GetString("Company_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string Company_EditModal {
            get {
                return ResourceManager.GetString("Company_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experiences.
        /// </summary>
        public static string Company_ExperienceCount {
            get {
                return ResourceManager.GetString("Company_ExperienceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create company. Please try again..
        /// </summary>
        public static string Company_FailedToCreate {
            get {
                return ResourceManager.GetString("Company_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete company..
        /// </summary>
        public static string Company_FailedToDelete {
            get {
                return ResourceManager.GetString("Company_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load company details..
        /// </summary>
        public static string Company_FailedToLoad {
            get {
                return ResourceManager.GetString("Company_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save company..
        /// </summary>
        public static string Company_FailedToSave {
            get {
                return ResourceManager.GetString("Company_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Education.
        /// </summary>
        public static string Education_Add {
            get {
                return ResourceManager.GetString("Education_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Institution.
        /// </summary>
        public static string Education_AddInstitution {
            get {
                return ResourceManager.GetString("Education_AddInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Education.
        /// </summary>
        public static string Education_CreateModal {
            get {
                return ResourceManager.GetString("Education_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this education entry? This action cannot be undone..
        /// </summary>
        public static string Education_DeleteMessage {
            get {
                return ResourceManager.GetString("Education_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Education.
        /// </summary>
        public static string Education_DeleteTitle {
            get {
                return ResourceManager.GetString("Education_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Education.
        /// </summary>
        public static string Education_EditModal {
            get {
                return ResourceManager.GetString("Education_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create education. Please try again..
        /// </summary>
        public static string Education_FailedToCreate {
            get {
                return ResourceManager.GetString("Education_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete education entry..
        /// </summary>
        public static string Education_FailedToDelete {
            get {
                return ResourceManager.GetString("Education_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load education details..
        /// </summary>
        public static string Education_FailedToLoad {
            get {
                return ResourceManager.GetString("Education_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education_Heading {
            get {
                return ResourceManager.GetString("Education_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions.
        /// </summary>
        public static string Education_Institutions {
            get {
                return ResourceManager.GetString("Education_Institutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no education entries..
        /// </summary>
        public static string Education_NoEntries {
            get {
                return ResourceManager.GetString("Education_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No institutions yet..
        /// </summary>
        public static string Education_NoInstitutions {
            get {
                return ResourceManager.GetString("Education_NoInstitutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education — Admin.
        /// </summary>
        public static string Education_PageTitle {
            get {
                return ResourceManager.GetString("Education_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage education entries, institutions, and translations.
        /// </summary>
        public static string Education_Subtitle {
            get {
                return ResourceManager.GetString("Education_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown institution.
        /// </summary>
        public static string Education_UnknownInstitution {
            get {
                return ResourceManager.GetString("Education_UnknownInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Experience.
        /// </summary>
        public static string Experience_Add {
            get {
                return ResourceManager.GetString("Experience_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string Experience_AddCompany {
            get {
                return ResourceManager.GetString("Experience_AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Experience_Companies {
            get {
                return ResourceManager.GetString("Experience_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Experience.
        /// </summary>
        public static string Experience_CreateModal {
            get {
                return ResourceManager.GetString("Experience_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this experience entry? This action cannot be undone..
        /// </summary>
        public static string Experience_DeleteMessage {
            get {
                return ResourceManager.GetString("Experience_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Experience.
        /// </summary>
        public static string Experience_DeleteTitle {
            get {
                return ResourceManager.GetString("Experience_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Experience.
        /// </summary>
        public static string Experience_EditModal {
            get {
                return ResourceManager.GetString("Experience_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create experience. Please try again..
        /// </summary>
        public static string Experience_FailedToCreate {
            get {
                return ResourceManager.GetString("Experience_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete experience entry..
        /// </summary>
        public static string Experience_FailedToDelete {
            get {
                return ResourceManager.GetString("Experience_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load experience details..
        /// </summary>
        public static string Experience_FailedToLoad {
            get {
                return ResourceManager.GetString("Experience_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience_Heading {
            get {
                return ResourceManager.GetString("Experience_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies yet..
        /// </summary>
        public static string Experience_NoCompanies {
            get {
                return ResourceManager.GetString("Experience_NoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no experience entries..
        /// </summary>
        public static string Experience_NoEntries {
            get {
                return ResourceManager.GetString("Experience_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience — Admin.
        /// </summary>
        public static string Experience_PageTitle {
            get {
                return ResourceManager.GetString("Experience_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage experience entries, companies, and translations.
        /// </summary>
        public static string Experience_Subtitle {
            get {
                return ResourceManager.GetString("Experience_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown company.
        /// </summary>
        public static string Experience_UnknownCompany {
            get {
                return ResourceManager.GetString("Experience_UnknownCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Institution.
        /// </summary>
        public static string Institution_CreateModal {
            get {
                return ResourceManager.GetString("Institution_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this institution? This action cannot be undone..
        /// </summary>
        public static string Institution_DeleteMessage {
            get {
                return ResourceManager.GetString("Institution_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Institution.
        /// </summary>
        public static string Institution_DeleteTitle {
            get {
                return ResourceManager.GetString("Institution_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Institution.
        /// </summary>
        public static string Institution_EditModal {
            get {
                return ResourceManager.GetString("Institution_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to educations.
        /// </summary>
        public static string Institution_EducationCount {
            get {
                return ResourceManager.GetString("Institution_EducationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create institution. Please try again..
        /// </summary>
        public static string Institution_FailedToCreate {
            get {
                return ResourceManager.GetString("Institution_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete institution..
        /// </summary>
        public static string Institution_FailedToDelete {
            get {
                return ResourceManager.GetString("Institution_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load institution details..
        /// </summary>
        public static string Institution_FailedToLoad {
            get {
                return ResourceManager.GetString("Institution_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save institution..
        /// </summary>
        public static string Institution_FailedToSave {
            get {
                return ResourceManager.GetString("Institution_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Introduction_Active {
            get {
                return ResourceManager.GetString("Introduction_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Introduction.
        /// </summary>
        public static string Introduction_Add {
            get {
                return ResourceManager.GetString("Introduction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar filename.
        /// </summary>
        public static string Introduction_AvatarFilename {
            get {
                return ResourceManager.GetString("Introduction_AvatarFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar.webp.
        /// </summary>
        public static string Introduction_AvatarPlaceholder {
            get {
                return ResourceManager.GetString("Introduction_AvatarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Introduction.
        /// </summary>
        public static string Introduction_CreateModal {
            get {
                return ResourceManager.GetString("Introduction_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this introduction? This action cannot be undone..
        /// </summary>
        public static string Introduction_DeleteMessage {
            get {
                return ResourceManager.GetString("Introduction_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Introduction.
        /// </summary>
        public static string Introduction_DeleteTitle {
            get {
                return ResourceManager.GetString("Introduction_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Introduction.
        /// </summary>
        public static string Introduction_EditModal {
            get {
                return ResourceManager.GetString("Introduction_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create introduction. Please try again..
        /// </summary>
        public static string Introduction_FailedToCreate {
            get {
                return ResourceManager.GetString("Introduction_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete introduction..
        /// </summary>
        public static string Introduction_FailedToDelete {
            get {
                return ResourceManager.GetString("Introduction_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load introduction details..
        /// </summary>
        public static string Introduction_FailedToLoad {
            get {
                return ResourceManager.GetString("Introduction_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction_Heading {
            get {
                return ResourceManager.GetString("Introduction_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Introduction_History {
            get {
                return ResourceManager.GetString("Introduction_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no introductions..
        /// </summary>
        public static string Introduction_NoEntries {
            get {
                return ResourceManager.GetString("Introduction_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction — Admin.
        /// </summary>
        public static string Introduction_PageTitle {
            get {
                return ResourceManager.GetString("Introduction_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pub Date.
        /// </summary>
        public static string Introduction_PubDate {
            get {
                return ResourceManager.GetString("Introduction_PubDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string Introduction_Scheduled {
            get {
                return ResourceManager.GetString("Introduction_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small avatar filename.
        /// </summary>
        public static string Introduction_SmallAvatarFilename {
            get {
                return ResourceManager.GetString("Introduction_SmallAvatarFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small_avatar.webp.
        /// </summary>
        public static string Introduction_SmallAvatarPlaceholder {
            get {
                return ResourceManager.GetString("Introduction_SmallAvatarPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage introductions and schedule publications.
        /// </summary>
        public static string Introduction_Subtitle {
            get {
                return ResourceManager.GetString("Introduction_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superseded.
        /// </summary>
        public static string Introduction_Superseded {
            get {
                return ResourceManager.GetString("Introduction_Superseded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Keywords_Add {
            get {
                return ResourceManager.GetString("Keywords_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level.
        /// </summary>
        public static string Keywords_AddLevel {
            get {
                return ResourceManager.GetString("Keywords_AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Keyword.
        /// </summary>
        public static string Keywords_CreateModal {
            get {
                return ResourceManager.GetString("Keywords_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this keyword? This will also remove it from any associated projects..
        /// </summary>
        public static string Keywords_DeleteMessage {
            get {
                return ResourceManager.GetString("Keywords_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Keyword.
        /// </summary>
        public static string Keywords_DeleteTitle {
            get {
                return ResourceManager.GetString("Keywords_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display on CV.
        /// </summary>
        public static string Keywords_DisplayOnCv {
            get {
                return ResourceManager.GetString("Keywords_DisplayOnCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Keyword.
        /// </summary>
        public static string Keywords_EditModal {
            get {
                return ResourceManager.GetString("Keywords_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create keyword. Please try again..
        /// </summary>
        public static string Keywords_FailedToCreate {
            get {
                return ResourceManager.GetString("Keywords_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete keyword..
        /// </summary>
        public static string Keywords_FailedToDelete {
            get {
                return ResourceManager.GetString("Keywords_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load keyword details..
        /// </summary>
        public static string Keywords_FailedToLoad {
            get {
                return ResourceManager.GetString("Keywords_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save keyword..
        /// </summary>
        public static string Keywords_FailedToSave {
            get {
                return ResourceManager.GetString("Keywords_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords_Heading {
            get {
                return ResourceManager.GetString("Keywords_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden from CV.
        /// </summary>
        public static string Keywords_HiddenFromCv {
            get {
                return ResourceManager.GetString("Keywords_HiddenFromCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} yet..
        /// </summary>
        public static string Keywords_NoKeywordsOfType {
            get {
                return ResourceManager.GetString("Keywords_NoKeywordsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proficiency levels defined yet..
        /// </summary>
        public static string Keywords_NoProficiency {
            get {
                return ResourceManager.GetString("Keywords_NoProficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords — Admin.
        /// </summary>
        public static string Keywords_PageTitle {
            get {
                return ResourceManager.GetString("Keywords_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency.
        /// </summary>
        public static string Keywords_Proficiency {
            get {
                return ResourceManager.GetString("Keywords_Proficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proficiency Levels.
        /// </summary>
        public static string Keywords_ProficiencyLevels {
            get {
                return ResourceManager.GetString("Keywords_ProficiencyLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Keywords_Scale {
            get {
                return ResourceManager.GetString("Keywords_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage keywords and proficiency levels.
        /// </summary>
        public static string Keywords_Subtitle {
            get {
                return ResourceManager.GetString("Keywords_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Keywords_Type {
            get {
                return ResourceManager.GetString("Keywords_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Keywords_Visible {
            get {
                return ResourceManager.GetString("Keywords_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible on CV.
        /// </summary>
        public static string Keywords_VisibleOnCv {
            get {
                return ResourceManager.GetString("Keywords_VisibleOnCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible only.
        /// </summary>
        public static string Keywords_VisibleOnly {
            get {
                return ResourceManager.GetString("Keywords_VisibleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        public static string Overview_KeywordPlural {
            get {
                return ResourceManager.GetString("Overview_KeywordPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyword.
        /// </summary>
        public static string Overview_KeywordSingular {
            get {
                return ResourceManager.GetString("Overview_KeywordSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Overview_Languages {
            get {
                return ResourceManager.GetString("Overview_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active introduction..
        /// </summary>
        public static string Overview_NoActiveIntroduction {
            get {
                return ResourceManager.GetString("Overview_NoActiveIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No education entries available..
        /// </summary>
        public static string Overview_NoEducation {
            get {
                return ResourceManager.GetString("Overview_NoEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No experiences available..
        /// </summary>
        public static string Overview_NoExperiences {
            get {
                return ResourceManager.GetString("Overview_NoExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keywords available..
        /// </summary>
        public static string Overview_NoKeywords {
            get {
                return ResourceManager.GetString("Overview_NoKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects available..
        /// </summary>
        public static string Overview_NoProjects {
            get {
                return ResourceManager.GetString("Overview_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Overview.
        /// </summary>
        public static string Overview_PageTitle {
            get {
                return ResourceManager.GetString("Overview_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Overview_Skills {
            get {
                return ResourceManager.GetString("Overview_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick preview of all CV sections..
        /// </summary>
        public static string Overview_Subtitle {
            get {
                return ResourceManager.GetString("Overview_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        public static string Overview_Technologies {
            get {
                return ResourceManager.GetString("Overview_Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Proficiency Level.
        /// </summary>
        public static string Proficiency_CreateModal {
            get {
                return ResourceManager.GetString("Proficiency_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this proficiency level? This action cannot be undone..
        /// </summary>
        public static string Proficiency_DeleteMessage {
            get {
                return ResourceManager.GetString("Proficiency_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Proficiency Level.
        /// </summary>
        public static string Proficiency_DeleteTitle {
            get {
                return ResourceManager.GetString("Proficiency_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Proficiency Level.
        /// </summary>
        public static string Proficiency_EditModal {
            get {
                return ResourceManager.GetString("Proficiency_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create proficiency. Please try again..
        /// </summary>
        public static string Proficiency_FailedToCreate {
            get {
                return ResourceManager.GetString("Proficiency_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete proficiency..
        /// </summary>
        public static string Proficiency_FailedToDelete {
            get {
                return ResourceManager.GetString("Proficiency_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load proficiency details..
        /// </summary>
        public static string Proficiency_FailedToLoad {
            get {
                return ResourceManager.GetString("Proficiency_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save proficiency..
        /// </summary>
        public static string Proficiency_FailedToSave {
            get {
                return ResourceManager.GetString("Proficiency_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        public static string Proficiency_KeywordCount {
            get {
                return ResourceManager.GetString("Proficiency_KeywordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale (0–100).
        /// </summary>
        public static string Proficiency_ScaleLabel {
            get {
                return ResourceManager.GetString("Proficiency_ScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string Projects_Add {
            get {
                return ResourceManager.GetString("Projects_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string Projects_CreateModal {
            get {
                return ResourceManager.GetString("Projects_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this project? This action cannot be undone..
        /// </summary>
        public static string Projects_DeleteMessage {
            get {
                return ResourceManager.GetString("Projects_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Project.
        /// </summary>
        public static string Projects_DeleteTitle {
            get {
                return ResourceManager.GetString("Projects_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string Projects_EditModal {
            get {
                return ResourceManager.GetString("Projects_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create project. Please try again..
        /// </summary>
        public static string Projects_FailedToCreate {
            get {
                return ResourceManager.GetString("Projects_FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete project..
        /// </summary>
        public static string Projects_FailedToDelete {
            get {
                return ResourceManager.GetString("Projects_FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load project details..
        /// </summary>
        public static string Projects_FailedToLoad {
            get {
                return ResourceManager.GetString("Projects_FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load keywords..
        /// </summary>
        public static string Projects_FailedToLoadKeywords {
            get {
                return ResourceManager.GetString("Projects_FailedToLoadKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects_Heading {
            get {
                return ResourceManager.GetString("Projects_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image filename.
        /// </summary>
        public static string Projects_ImageFilename {
            get {
                return ResourceManager.GetString("Projects_ImageFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string Projects_ImageUrl {
            get {
                return ResourceManager.GetString("Projects_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Projects_Info {
            get {
                return ResourceManager.GetString("Projects_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (short tagline).
        /// </summary>
        public static string Projects_InfoTagline {
            get {
                return ResourceManager.GetString("Projects_InfoTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects..
        /// </summary>
        public static string Projects_NoEntries {
            get {
                return ResourceManager.GetString("Projects_NoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects — Admin.
        /// </summary>
        public static string Projects_PageTitle {
            get {
                return ResourceManager.GetString("Projects_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string Projects_ProjectName {
            get {
                return ResourceManager.GetString("Projects_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL.
        /// </summary>
        public static string Projects_ProjectUrl {
            get {
                return ResourceManager.GetString("Projects_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage portfolio projects and translations.
        /// </summary>
        public static string Projects_Subtitle {
            get {
                return ResourceManager.GetString("Projects_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Projects_Visit {
            get {
                return ResourceManager.GetString("Projects_Visit", resourceCulture);
            }
        }
    }
}
