//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdeasStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdeasStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Web.Admin.Resources.IdeasStrings", typeof(IdeasStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Domains.
        /// </summary>
        public static string AllDomains {
            get {
                return ResourceManager.GetString("AllDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Priorities.
        /// </summary>
        public static string AllPriorities {
            get {
                return ResourceManager.GetString("AllPriorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Statuses.
        /// </summary>
        public static string AllStatuses {
            get {
                return ResourceManager.GetString("AllStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        public static string AllTags {
            get {
                return ResourceManager.GetString("AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string Detail_AddNote {
            get {
                return ResourceManager.GetString("Detail_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note….
        /// </summary>
        public static string Detail_AddNotePlaceholder {
            get {
                return ResourceManager.GetString("Detail_AddNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Ideas.
        /// </summary>
        public static string Detail_BackButton {
            get {
                return ResourceManager.GetString("Detail_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas.
        /// </summary>
        public static string Detail_BackToIdeas {
            get {
                return ResourceManager.GetString("Detail_BackToIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description yet..
        /// </summary>
        public static string Detail_NoDescription {
            get {
                return ResourceManager.GetString("Detail_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Detail_Notes {
            get {
                return ResourceManager.GetString("Detail_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea not found..
        /// </summary>
        public static string Detail_NotFound {
            get {
                return ResourceManager.GetString("Detail_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0}.
        /// </summary>
        public static string Detail_Updated {
            get {
                return ResourceManager.GetString("Detail_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load idea details..
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea Bank.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Idea.
        /// </summary>
        public static string Idea_CreateModal {
            get {
                return ResourceManager.GetString("Idea_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Idea.
        /// </summary>
        public static string Idea_EditModal {
            get {
                return ResourceManager.GetString("Idea_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Idea.
        /// </summary>
        public static string NewIdea {
            get {
                return ResourceManager.GetString("NewIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tag.
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ideas yet. Capture your first spark!.
        /// </summary>
        public static string NoIdeas {
            get {
                return ResourceManager.GetString("NoIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ideas match the current filters..
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags yet..
        /// </summary>
        public static string NoTags {
            get {
                return ResourceManager.GetString("NoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea Bank.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-liner hook or intent (optional).
        /// </summary>
        public static string SummaryPlaceholder {
            get {
                return ResourceManager.GetString("SummaryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tag.
        /// </summary>
        public static string Tag_CreateModal {
            get {
                return ResourceManager.GetString("Tag_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tag.
        /// </summary>
        public static string Tag_EditModal {
            get {
                return ResourceManager.GetString("Tag_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Name.
        /// </summary>
        public static string Tag_Name {
            get {
                return ResourceManager.GetString("Tag_Name", resourceCulture);
            }
        }
    }
}
