//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InboxStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InboxStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Web.Admin.Resources.InboxStrings", typeof(InboxStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss the request from &quot;{0}&quot;?.
        /// </summary>
        public static string Dismiss_Message {
            get {
                return ResourceManager.GetString("Dismiss_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss Request.
        /// </summary>
        public static string Dismiss_Title {
            get {
                return ResourceManager.GetString("Dismiss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as spam.
        /// </summary>
        public static string MarkAsSpam {
            get {
                return ResourceManager.GetString("MarkAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Spam.
        /// </summary>
        public static string MarkSpam_Button {
            get {
                return ResourceManager.GetString("MarkSpam_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark the request from &quot;{0}&quot; as spam?.
        /// </summary>
        public static string MarkSpam_Message {
            get {
                return ResourceManager.GetString("MarkSpam_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Spam.
        /// </summary>
        public static string MarkSpam_Title {
            get {
                return ResourceManager.GetString("MarkSpam_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests match the current filter..
        /// </summary>
        public static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contact requests received yet..
        /// </summary>
        public static string NoRequests {
            get {
                return ResourceManager.GetString("NoRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string Promote_Button {
            get {
                return ResourceManager.GetString("Promote_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new company.
        /// </summary>
        public static string Promote_CreateNew {
            get {
                return ResourceManager.GetString("Promote_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Select or create company —.
        /// </summary>
        public static string Promote_SelectCompany {
            get {
                return ResourceManager.GetString("Promote_SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Interaction.
        /// </summary>
        public static string Promote_Title {
            get {
                return ResourceManager.GetString("Promote_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to interaction.
        /// </summary>
        public static string PromoteToInteraction {
            get {
                return ResourceManager.GetString("PromoteToInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} request(s).
        /// </summary>
        public static string ShowingCount {
            get {
                return ResourceManager.GetString("ShowingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact requests submitted via the CV form..
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissed.
        /// </summary>
        public static string Tab_Dismissed {
            get {
                return ResourceManager.GetString("Tab_Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Tab_New {
            get {
                return ResourceManager.GetString("Tab_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted.
        /// </summary>
        public static string Tab_Promoted {
            get {
                return ResourceManager.GetString("Tab_Promoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string Tab_Spam {
            get {
                return ResourceManager.GetString("Tab_Spam", resourceCulture);
            }
        }
    }
}
