//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Web.Admin.Resources.LayoutStrings", typeof(LayoutStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulku Admin.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        public static string Dashboard_Actions {
            get {
                return ResourceManager.GetString("Dashboard_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All relationships are on track..
        /// </summary>
        public static string Dashboard_AllOnTrack {
            get {
                return ResourceManager.GetString("Dashboard_AllOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention Needed.
        /// </summary>
        public static string Dashboard_AttentionNeeded {
            get {
                return ResourceManager.GetString("Dashboard_AttentionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companies.
        /// </summary>
        public static string Dashboard_Companies {
            get {
                return ResourceManager.GetString("Dashboard_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Overview.
        /// </summary>
        public static string Dashboard_CvOverview {
            get {
                return ResourceManager.GetString("Dashboard_CvOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to education.
        /// </summary>
        public static string Dashboard_Education {
            get {
                return ResourceManager.GetString("Dashboard_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to experience.
        /// </summary>
        public static string Dashboard_Experience {
            get {
                return ResourceManager.GetString("Dashboard_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going cold.
        /// </summary>
        public static string Dashboard_GoingCold {
            get {
                return ResourceManager.GetString("Dashboard_GoingCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Heading {
            get {
                return ResourceManager.GetString("Dashboard_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea Bank.
        /// </summary>
        public static string Dashboard_IdeaBank {
            get {
                return ResourceManager.GetString("Dashboard_IdeaBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ideas.
        /// </summary>
        public static string Dashboard_Ideas {
            get {
                return ResourceManager.GetString("Dashboard_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Dashboard_Inbox {
            get {
                return ResourceManager.GetString("Dashboard_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the idea bank.
        /// </summary>
        public static string Dashboard_InTheIdeaBank {
            get {
                return ResourceManager.GetString("Dashboard_InTheIdeaBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        public static string Dashboard_Keywords {
            get {
                return ResourceManager.GetString("Dashboard_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest activity.
        /// </summary>
        public static string Dashboard_LatestActivity {
            get {
                return ResourceManager.GetString("Dashboard_LatestActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest new contact requests.
        /// </summary>
        public static string Dashboard_LatestNewRequests {
            get {
                return ResourceManager.GetString("Dashboard_LatestNewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage CV.
        /// </summary>
        public static string Dashboard_ManageCv {
            get {
                return ResourceManager.GetString("Dashboard_ManageCv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Dashboard_Network {
            get {
                return ResourceManager.GetString("Dashboard_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string Dashboard_New {
            get {
                return ResourceManager.GetString("Dashboard_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ideas yet..
        /// </summary>
        public static string Dashboard_NoIdeasYet {
            get {
                return ResourceManager.GetString("Dashboard_NoIdeasYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interactions yet..
        /// </summary>
        public static string Dashboard_NoInteractionsYet {
            get {
                return ResourceManager.GetString("Dashboard_NoInteractionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new requests — inbox is clear..
        /// </summary>
        public static string Dashboard_NoNewRequests {
            get {
                return ResourceManager.GetString("Dashboard_NoNewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Dashboard_Overdue {
            get {
                return ResourceManager.GetString("Dashboard_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue actions &amp; cold relationships.
        /// </summary>
        public static string Dashboard_OverdueAndCold {
            get {
                return ResourceManager.GetString("Dashboard_OverdueAndCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard — Kulku Admin.
        /// </summary>
        public static string Dashboard_PageTitle {
            get {
                return ResourceManager.GetString("Dashboard_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Dashboard_Portfolio {
            get {
                return ResourceManager.GetString("Dashboard_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string Dashboard_Projects {
            get {
                return ResourceManager.GetString("Dashboard_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Ideas.
        /// </summary>
        public static string Dashboard_RecentIdeas {
            get {
                return ResourceManager.GetString("Dashboard_RecentIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently updated ideas.
        /// </summary>
        public static string Dashboard_RecentlyUpdatedIdeas {
            get {
                return ResourceManager.GetString("Dashboard_RecentlyUpdatedIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Requests.
        /// </summary>
        public static string Dashboard_RecentRequests {
            get {
                return ResourceManager.GetString("Dashboard_RecentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationships.
        /// </summary>
        public static string Dashboard_Relationships {
            get {
                return ResourceManager.GetString("Dashboard_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase projects.
        /// </summary>
        public static string Dashboard_ShowcaseProjects {
            get {
                return ResourceManager.GetString("Dashboard_ShowcaseProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked relationships.
        /// </summary>
        public static string Dashboard_TrackedRelationships {
            get {
                return ResourceManager.GetString("Dashboard_TrackedRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread contact requests.
        /// </summary>
        public static string Dashboard_UnreadRequests {
            get {
                return ResourceManager.GetString("Dashboard_UnreadRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back,.
        /// </summary>
        public static string Dashboard_Welcome {
            get {
                return ResourceManager.GetString("Dashboard_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error_Heading {
            get {
                return ResourceManager.GetString("Error_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_PageTitle {
            get {
                return ResourceManager.GetString("Error_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        public static string Error_RequestId {
            get {
                return ResourceManager.GetString("Error_RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Management.
        /// </summary>
        public static string Landing_CvManagement {
            get {
                return ResourceManager.GetString("Landing_CvManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your introduction, education, work experience, and skill keywords across multiple languages..
        /// </summary>
        public static string Landing_CvManagementDesc {
            get {
                return ResourceManager.GetString("Landing_CvManagementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A personal management dashboard for maintaining your professional portfolio, CV content, project showcases, and developer workflow..
        /// </summary>
        public static string Landing_Description {
            get {
                return ResourceManager.GetString("Landing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to get in touch?.
        /// </summary>
        public static string Landing_GetInTouch {
            get {
                return ResourceManager.GetString("Landing_GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idea Bank.
        /// </summary>
        public static string Landing_IdeaBank {
            get {
                return ResourceManager.GetString("Landing_IdeaBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture and organize project ideas, feature requests, and inspiration for future work..
        /// </summary>
        public static string Landing_IdeaBankDesc {
            get {
                return ResourceManager.GetString("Landing_IdeaBankDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Landing_Network {
            get {
                return ResourceManager.GetString("Landing_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track companies, interactions, and networking activity to stay on top of your professional outreach..
        /// </summary>
        public static string Landing_NetworkDesc {
            get {
                return ResourceManager.GetString("Landing_NetworkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Portfolio.
        /// </summary>
        public static string Landing_ProjectPortfolio {
            get {
                return ResourceManager.GetString("Landing_ProjectPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcase your projects with descriptions, images, and links. Content feeds directly to the public site..
        /// </summary>
        public static string Landing_ProjectPortfolioDesc {
            get {
                return ResourceManager.GetString("Landing_ProjectPortfolioDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Landing_Register {
            get {
                return ResourceManager.GetString("Landing_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is currently closed. If you&apos;d like to reach out, you can send me a message through my contact form..
        /// </summary>
        public static string Landing_RegistrationClosed {
            get {
                return ResourceManager.GetString("Landing_RegistrationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message.
        /// </summary>
        public static string Landing_SendMessage {
            get {
                return ResourceManager.GetString("Landing_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Landing_SignIn {
            get {
                return ResourceManager.GetString("Landing_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string Language_en {
            get {
                return ResourceManager.GetString("Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FI.
        /// </summary>
        public static string Language_fi {
            get {
                return ResourceManager.GetString("Language_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Nav_Companies {
            get {
                return ResourceManager.GetString("Nav_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cv.
        /// </summary>
        public static string Nav_Cv {
            get {
                return ResourceManager.GetString("Nav_Cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Nav_Education {
            get {
                return ResourceManager.GetString("Nav_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Nav_Experience {
            get {
                return ResourceManager.GetString("Nav_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas.
        /// </summary>
        public static string Nav_Ideas {
            get {
                return ResourceManager.GetString("Nav_Ideas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Nav_Inbox {
            get {
                return ResourceManager.GetString("Nav_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Nav_Introduction {
            get {
                return ResourceManager.GetString("Nav_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Nav_Keywords {
            get {
                return ResourceManager.GetString("Nav_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Interaction.
        /// </summary>
        public static string Nav_LogInteraction {
            get {
                return ResourceManager.GetString("Nav_LogInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Nav_Network {
            get {
                return ResourceManager.GetString("Nav_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Nav_Overview {
            get {
                return ResourceManager.GetString("Nav_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Nav_Projects {
            get {
                return ResourceManager.GetString("Nav_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Nav_Register {
            get {
                return ResourceManager.GetString("Nav_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound_Heading {
            get {
                return ResourceManager.GetString("NotFound_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the content you are looking for does not exist..
        /// </summary>
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open menu.
        /// </summary>
        public static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rejoin..
        /// </summary>
        public static string Reconnect_Failed {
            get {
                return ResourceManager.GetString("Reconnect_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has been paused by the server..
        /// </summary>
        public static string Reconnect_Paused {
            get {
                return ResourceManager.GetString("Reconnect_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reload the page..
        /// </summary>
        public static string Reconnect_PleaseReload {
            get {
                return ResourceManager.GetString("Reconnect_PleaseReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoin failed... trying again in.
        /// </summary>
        public static string Reconnect_RejoinFailed {
            get {
                return ResourceManager.GetString("Reconnect_RejoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoining the server....
        /// </summary>
        public static string Reconnect_Rejoining {
            get {
                return ResourceManager.GetString("Reconnect_Rejoining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resume the session..
        /// </summary>
        public static string Reconnect_ResumeFailed {
            get {
                return ResourceManager.GetString("Reconnect_ResumeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retry or reload the page..
        /// </summary>
        public static string Reconnect_RetryOrReload {
            get {
                return ResourceManager.GetString("Reconnect_RetryOrReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        public static string Reconnect_Seconds {
            get {
                return ResourceManager.GetString("Reconnect_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle sidebar.
        /// </summary>
        public static string ToggleSidebar {
            get {
                return ResourceManager.GetString("ToggleSidebar", resourceCulture);
            }
        }
    }
}
