//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulku.Web.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetworkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kulku.Web.Admin.Resources.NetworkStrings", typeof(NetworkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All channels.
        /// </summary>
        public static string ActivityLog_AllChannels {
            get {
                return ResourceManager.GetString("ActivityLog_AllChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All companies.
        /// </summary>
        public static string ActivityLog_AllCompanies {
            get {
                return ResourceManager.GetString("ActivityLog_AllCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string ActivityLog_ClearFilters {
            get {
                return ResourceManager.GetString("ActivityLog_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ActivityLog_Dashboard {
            get {
                return ResourceManager.GetString("ActivityLog_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Log.
        /// </summary>
        public static string ActivityLog_Heading {
            get {
                return ResourceManager.GetString("ActivityLog_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound.
        /// </summary>
        public static string ActivityLog_Inbound {
            get {
                return ResourceManager.GetString("ActivityLog_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log your first interaction.
        /// </summary>
        public static string ActivityLog_LogFirst {
            get {
                return ResourceManager.GetString("ActivityLog_LogFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interactions match the current filters..
        /// </summary>
        public static string ActivityLog_NoMatch {
            get {
                return ResourceManager.GetString("ActivityLog_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound.
        /// </summary>
        public static string ActivityLog_Outbound {
            get {
                return ResourceManager.GetString("ActivityLog_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Log.
        /// </summary>
        public static string ActivityLog_PageTitle {
            get {
                return ResourceManager.GetString("ActivityLog_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ActivityLog_Search {
            get {
                return ResourceManager.GetString("ActivityLog_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary or company name….
        /// </summary>
        public static string ActivityLog_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ActivityLog_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} of {1} interaction(s).
        /// </summary>
        public static string ActivityLog_ShowingCount {
            get {
                return ResourceManager.GetString("ActivityLog_ShowingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more ({0} remaining).
        /// </summary>
        public static string ActivityLog_ShowMore {
            get {
                return ResourceManager.GetString("ActivityLog_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full interaction history across all companies..
        /// </summary>
        public static string ActivityLog_Subtitle {
            get {
                return ResourceManager.GetString("ActivityLog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string Companies_AllCategories {
            get {
                return ResourceManager.GetString("Companies_AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string Companies_Contacts {
            get {
                return ResourceManager.GetString("Companies_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Company.
        /// </summary>
        public static string Companies_Enroll {
            get {
                return ResourceManager.GetString("Companies_Enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies_Heading {
            get {
                return ResourceManager.GetString("Companies_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interactions.
        /// </summary>
        public static string Companies_Interactions {
            get {
                return ResourceManager.GetString("Companies_Interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last:.
        /// </summary>
        public static string Companies_Last {
            get {
                return ResourceManager.GetString("Companies_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to company….
        /// </summary>
        public static string Companies_LinkToCompany {
            get {
                return ResourceManager.GetString("Companies_LinkToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Companies_ListView {
            get {
                return ResourceManager.GetString("Companies_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string Companies_NewCategory {
            get {
                return ResourceManager.GetString("Companies_NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Personal Contact.
        /// </summary>
        public static string Companies_NewPersonalContact {
            get {
                return ResourceManager.GetString("Companies_NewPersonalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories yet..
        /// </summary>
        public static string Companies_NoCategories {
            get {
                return ResourceManager.GetString("Companies_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies tracked yet..
        /// </summary>
        public static string Companies_NoCompanies {
            get {
                return ResourceManager.GetString("Companies_NoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies match the current filters..
        /// </summary>
        public static string Companies_NoMatch {
            get {
                return ResourceManager.GetString("Companies_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal contacts. These are people not currently affiliated with a company..
        /// </summary>
        public static string Companies_NoPersonalContacts {
            get {
                return ResourceManager.GetString("Companies_NoPersonalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies_PageTitle {
            get {
                return ResourceManager.GetString("Companies_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus list — keep it small, quality relationships only..
        /// </summary>
        public static string Companies_Subtitle {
            get {
                return ResourceManager.GetString("Companies_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to companies.
        /// </summary>
        public static string Detail_BackToCompanies {
            get {
                return ResourceManager.GetString("Detail_BackToCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found.
        /// </summary>
        public static string Detail_CompanyNotFoundTitle {
            get {
                return ResourceManager.GetString("Detail_CompanyNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Detail_Contacts {
            get {
                return ResourceManager.GetString("Detail_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company.
        /// </summary>
        public static string Detail_EditCompany {
            get {
                return ResourceManager.GetString("Detail_EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Timeline.
        /// </summary>
        public static string Detail_InteractionTimeline {
            get {
                return ResourceManager.GetString("Detail_InteractionTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Interaction.
        /// </summary>
        public static string Detail_LogInteraction {
            get {
                return ResourceManager.GetString("Detail_LogInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log one now..
        /// </summary>
        public static string Detail_LogOneNow {
            get {
                return ResourceManager.GetString("Detail_LogOneNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to….
        /// </summary>
        public static string Detail_MoveTo {
            get {
                return ResourceManager.GetString("Detail_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts yet..
        /// </summary>
        public static string Detail_NoContacts {
            get {
                return ResourceManager.GetString("Detail_NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interactions recorded..
        /// </summary>
        public static string Detail_NoInteractions {
            get {
                return ResourceManager.GetString("Detail_NoInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found..
        /// </summary>
        public static string Detail_NotFound {
            get {
                return ResourceManager.GetString("Detail_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove affiliation (personal).
        /// </summary>
        public static string Detail_RemoveAffiliation {
            get {
                return ResourceManager.GetString("Detail_RemoveAffiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage:.
        /// </summary>
        public static string Detail_Stage {
            get {
                return ResourceManager.GetString("Detail_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unnamed).
        /// </summary>
        public static string Detail_Unnamed {
            get {
                return ResourceManager.GetString("Detail_Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm intro.
        /// </summary>
        public static string InteractionCard_WarmIntro {
            get {
                return ResourceManager.GetString("InteractionCard_WarmIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn URL.
        /// </summary>
        public static string LinkedInUrl {
            get {
                return ResourceManager.GetString("LinkedInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete, time-bound action.
        /// </summary>
        public static string LogInteraction_ActionPlaceholder {
            get {
                return ResourceManager.GetString("LogInteraction_ActionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to dashboard.
        /// </summary>
        public static string LogInteraction_BackToDashboard {
            get {
                return ResourceManager.GetString("LogInteraction_BackToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared taxonomy with Idea Bank..
        /// </summary>
        public static string LogInteraction_CategorySubtitle {
            get {
                return ResourceManager.GetString("LogInteraction_CategorySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleague.
        /// </summary>
        public static string LogInteraction_Colleague {
            get {
                return ResourceManager.GetString("LogInteraction_Colleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company categories.
        /// </summary>
        public static string LogInteraction_CompanyCategories {
            get {
                return ResourceManager.GetString("LogInteraction_CompanyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company contacts.
        /// </summary>
        public static string LogInteraction_CompanyContacts {
            get {
                return ResourceManager.GetString("LogInteraction_CompanyContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company history.
        /// </summary>
        public static string LogInteraction_CompanyHistory {
            get {
                return ResourceManager.GetString("LogInteraction_CompanyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing company to see its history. New companies start empty..
        /// </summary>
        public static string LogInteraction_CompanyHistoryEmpty {
            get {
                return ResourceManager.GetString("LogInteraction_CompanyHistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction details.
        /// </summary>
        public static string LogInteraction_Details {
            get {
                return ResourceManager.GetString("LogInteraction_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string LogInteraction_DueDate {
            get {
                return ResourceManager.GetString("LogInteraction_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string LogInteraction_Friend {
            get {
                return ResourceManager.GetString("LogInteraction_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log interaction.
        /// </summary>
        public static string LogInteraction_Heading {
            get {
                return ResourceManager.GetString("LogInteraction_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — New contact —.
        /// </summary>
        public static string LogInteraction_NewContact {
            get {
                return ResourceManager.GetString("LogInteraction_NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next action (optional).
        /// </summary>
        public static string LogInteraction_NextAction {
            get {
                return ResourceManager.GetString("LogInteraction_NextAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories configured..
        /// </summary>
        public static string LogInteraction_NoCategories {
            get {
                return ResourceManager.GetString("LogInteraction_NoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No prior interactions recorded..
        /// </summary>
        public static string LogInteraction_NoPriorInteractions {
            get {
                return ResourceManager.GetString("LogInteraction_NoPriorInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string LogInteraction_Other {
            get {
                return ResourceManager.GetString("LogInteraction_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log interaction.
        /// </summary>
        public static string LogInteraction_PageTitle {
            get {
                return ResourceManager.GetString("LogInteraction_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Personal.
        /// </summary>
        public static string LogInteraction_Personal {
            get {
                return ResourceManager.GetString("LogInteraction_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name.
        /// </summary>
        public static string LogInteraction_PersonName {
            get {
                return ResourceManager.GetString("LogInteraction_PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string LogInteraction_Preview {
            get {
                return ResourceManager.GetString("LogInteraction_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred by (name/context).
        /// </summary>
        public static string LogInteraction_ReferredBy {
            get {
                return ResourceManager.GetString("LogInteraction_ReferredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string LogInteraction_Reset {
            get {
                return ResourceManager.GetString("LogInteraction_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save interaction.
        /// </summary>
        public static string LogInteraction_SaveInteraction {
            get {
                return ResourceManager.GetString("LogInteraction_SaveInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an enrolled company to link this interaction..
        /// </summary>
        public static string LogInteraction_SelectCompany {
            get {
                return ResourceManager.GetString("LogInteraction_SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies are usually created here. Link history when possible..
        /// </summary>
        public static string LogInteraction_Subtitle {
            get {
                return ResourceManager.GetString("LogInteraction_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title/role.
        /// </summary>
        public static string LogInteraction_TitleRole {
            get {
                return ResourceManager.GetString("LogInteraction_TitleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update categories.
        /// </summary>
        public static string LogInteraction_UpdateCategories {
            get {
                return ResourceManager.GetString("LogInteraction_UpdateCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm intro (friend / colleague).
        /// </summary>
        public static string LogInteraction_WarmIntro {
            get {
                return ResourceManager.GetString("LogInteraction_WarmIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap contextual color for the badge..
        /// </summary>
        public static string NetworkCategory_ColorHelp {
            get {
                return ResourceManager.GetString("NetworkCategory_ColorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color token.
        /// </summary>
        public static string NetworkCategory_ColorToken {
            get {
                return ResourceManager.GetString("NetworkCategory_ColorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string NetworkCategory_EditTitle {
            get {
                return ResourceManager.GetString("NetworkCategory_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string NetworkCategory_NewTitle {
            get {
                return ResourceManager.GetString("NetworkCategory_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — None —.
        /// </summary>
        public static string NetworkCategory_NoneOption {
            get {
                return ResourceManager.GetString("NetworkCategory_NoneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All companies are already enrolled in the network..
        /// </summary>
        public static string NetworkCompany_AllEnrolled {
            get {
                return ResourceManager.GetString("NetworkCompany_AllEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp; Enroll.
        /// </summary>
        public static string NetworkCompany_CreateAndEnrollButton {
            get {
                return ResourceManager.GetString("NetworkCompany_CreateAndEnrollButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp; Enroll Company.
        /// </summary>
        public static string NetworkCompany_CreateAndEnrollTitle {
            get {
                return ResourceManager.GetString("NetworkCompany_CreateAndEnrollTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Network Company.
        /// </summary>
        public static string NetworkCompany_CreateModal {
            get {
                return ResourceManager.GetString("NetworkCompany_CreateModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string NetworkCompany_CreateNew {
            get {
                return ResourceManager.GetString("NetworkCompany_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Network Company.
        /// </summary>
        public static string NetworkCompany_EditModal {
            get {
                return ResourceManager.GetString("NetworkCompany_EditModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Network Profile.
        /// </summary>
        public static string NetworkCompany_EditProfileTitle {
            get {
                return ResourceManager.GetString("NetworkCompany_EditProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        public static string NetworkCompany_EnrollButton {
            get {
                return ResourceManager.GetString("NetworkCompany_EnrollButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Company.
        /// </summary>
        public static string NetworkCompany_EnrollTitle {
            get {
                return ResourceManager.GetString("NetworkCompany_EnrollTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick existing.
        /// </summary>
        public static string NetworkCompany_PickExisting {
            get {
                return ResourceManager.GetString("NetworkCompany_PickExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Helsinki, Finland.
        /// </summary>
        public static string NetworkCompany_RegionPlaceholder {
            get {
                return ResourceManager.GetString("NetworkCompany_RegionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Select a company —.
        /// </summary>
        public static string NetworkCompany_SelectCompany {
            get {
                return ResourceManager.GetString("NetworkCompany_SelectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string NetworkContact_EditTitle {
            get {
                return ResourceManager.GetString("NetworkContact_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string NetworkContact_LinkedIn {
            get {
                return ResourceManager.GetString("NetworkContact_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        public static string NetworkContact_NewTitle {
            get {
                return ResourceManager.GetString("NetworkContact_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title / Role.
        /// </summary>
        public static string NetworkContact_TitleRole {
            get {
                return ResourceManager.GetString("NetworkContact_TitleRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} actions.
        /// </summary>
        public static string Overview_ActionCount {
            get {
                return ResourceManager.GetString("Overview_ActionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string Overview_Active {
            get {
                return ResourceManager.GetString("Overview_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity log.
        /// </summary>
        public static string Overview_ActivityLog {
            get {
                return ResourceManager.GetString("Overview_ActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All relationships are on track..
        /// </summary>
        public static string Overview_AllOnTrack {
            get {
                return ResourceManager.GetString("Overview_AllOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention Needed.
        /// </summary>
        public static string Overview_AttentionNeeded {
            get {
                return ResourceManager.GetString("Overview_AttentionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue actions and relationships going cold..
        /// </summary>
        public static string Overview_AttentionSubtitle {
            get {
                return ResourceManager.GetString("Overview_AttentionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left border color:.
        /// </summary>
        public static string Overview_BorderColorLegend {
            get {
                return ResourceManager.GetString("Overview_BorderColorLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cold (&gt;6mo).
        /// </summary>
        public static string Overview_ColdLegend {
            get {
                return ResourceManager.GetString("Overview_ColdLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Overview_Companies {
            get {
                return ResourceManager.GetString("Overview_Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider checking in.
        /// </summary>
        public static string Overview_ConsiderCheckingIn {
            get {
                return ResourceManager.GetString("Overview_ConsiderCheckingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cooling (3–6mo).
        /// </summary>
        public static string Overview_CoolingLegend {
            get {
                return ResourceManager.GetString("Overview_CoolingLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} d overdue.
        /// </summary>
        public static string Overview_DaysOverdue {
            get {
                return ResourceManager.GetString("Overview_DaysOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every tracked company — coldest relationships first..
        /// </summary>
        public static string Overview_DirectorySubtitle {
            get {
                return ResourceManager.GetString("Overview_DirectorySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow-ups.
        /// </summary>
        public static string Overview_FollowUps {
            get {
                return ResourceManager.GetString("Overview_FollowUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fresh (&lt;3mo).
        /// </summary>
        public static string Overview_FreshLegend {
            get {
                return ResourceManager.GetString("Overview_FreshLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to going cold.
        /// </summary>
        public static string Overview_GoingCold {
            get {
                return ResourceManager.GetString("Overview_GoingCold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going cold.
        /// </summary>
        public static string Overview_GoingColdBadge {
            get {
                return ResourceManager.GetString("Overview_GoingColdBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Overview.
        /// </summary>
        public static string Overview_Heading {
            get {
                return ResourceManager.GetString("Overview_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your interaction journal..
        /// </summary>
        public static string Overview_JournalSubtitle {
            get {
                return ResourceManager.GetString("Overview_JournalSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Activity.
        /// </summary>
        public static string Overview_LatestActivity {
            get {
                return ResourceManager.GetString("Overview_LatestActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log interaction.
        /// </summary>
        public static string Overview_LogInteraction {
            get {
                return ResourceManager.GetString("Overview_LogInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies tracked yet. Enroll companies from the Companies page..
        /// </summary>
        public static string Overview_NoCompaniesTracked {
            get {
                return ResourceManager.GetString("Overview_NoCompaniesTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no history.
        /// </summary>
        public static string Overview_NoHistoryLegend {
            get {
                return ResourceManager.GetString("Overview_NoHistoryLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relationships match the current filters..
        /// </summary>
        public static string Overview_NoRelationshipsMatch {
            get {
                return ResourceManager.GetString("Overview_NoRelationshipsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overdue.
        /// </summary>
        public static string Overview_Overdue {
            get {
                return ResourceManager.GetString("Overview_Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string Overview_OverdueLabel {
            get {
                return ResourceManager.GetString("Overview_OverdueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Overview.
        /// </summary>
        public static string Overview_PageTitle {
            get {
                return ResourceManager.GetString("Overview_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline:.
        /// </summary>
        public static string Overview_Pipeline {
            get {
                return ResourceManager.GetString("Overview_Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} relationships.
        /// </summary>
        public static string Overview_RelationshipCount {
            get {
                return ResourceManager.GetString("Overview_RelationshipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Directory.
        /// </summary>
        public static string Overview_RelationshipDirectory {
            get {
                return ResourceManager.GetString("Overview_RelationshipDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationships.
        /// </summary>
        public static string Overview_Relationships {
            get {
                return ResourceManager.GetString("Overview_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search name, region, contact….
        /// </summary>
        public static string Overview_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Overview_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing up to 10 most recent..
        /// </summary>
        public static string Overview_ShowingRecent {
            get {
                return ResourceManager.GetString("Overview_ShowingRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your professional network — who you know, what happened, and where to reconnect..
        /// </summary>
        public static string Overview_Subtitle {
            get {
                return ResourceManager.GetString("Overview_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (12mo).
        /// </summary>
        public static string Overview_TwelveMonths {
            get {
                return ResourceManager.GetString("Overview_TwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View full history.
        /// </summary>
        public static string Overview_ViewFullHistory {
            get {
                return ResourceManager.GetString("Overview_ViewFullHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline.
        /// </summary>
        public static string Pipeline {
            get {
                return ResourceManager.GetString("Pipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No companies.
        /// </summary>
        public static string PipelineColumn_NoCompanies {
            get {
                return ResourceManager.GetString("PipelineColumn_NoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string RelationshipRow_Days {
            get {
                return ResourceManager.GetString("RelationshipRow_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last touch:.
        /// </summary>
        public static string RelationshipRow_LastTouch {
            get {
                return ResourceManager.GetString("RelationshipRow_LastTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interactions recorded yet.
        /// </summary>
        public static string RelationshipRow_NoInteractions {
            get {
                return ResourceManager.GetString("RelationshipRow_NoInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string RelationshipRow_Since {
            get {
                return ResourceManager.GetString("RelationshipRow_Since", resourceCulture);
            }
        }
    }
}
